// AUTO-GENERATED by June — do not edit. Lazy loaders for client:* islands.
// Maps each island name to a loader that resolves its component; hydrateIslands uses it.
export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {
  "EarlyAccess": () => import("./EarlyAccess").then((m) => m.EarlyAccess),
};
